[package]
name = "json"
version = "0.2.1"
summary = "Test JSON parsing library for local Suture and Inscribe integration."

[source]
git = "D:/GitHub/Repositories/Mentalogue"

[build]
entry = "testprojects/jsonlib/lib.mtl"
